version: '3'
services:
    datastore:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=1234
            - POSTGRES_USER=postgres
        volumes:
            - /var/lib/postgresql
