name: ci

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.8]

        steps:
            -   uses: actions/checkout@v2

            -   name: install pipenv requirement
                run: 
                    pip install pipenv

            -   name: install requirements
                run: |
                    pip install pipenv
                    make install_requirements_dev

            -   name: run continuous integration process
                run:
                    make ci
